apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taas-sv-pvc
  namespace: taas-sv-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi