apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtserver-deployment
  namespace: taas-sv-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtserver
  template:
    metadata:
      labels:
        app: virtserver
    spec:
      containers:
      - name: virtserver
        image: smartbear/ready-api-virtserver:latest
        ports:
        - containerPort: 9090
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8002
        - containerPort: 8003
        - containerPort: 8004
        - containerPort: 8005
        - containerPort: 8006
        - containerPort: 8007
        - containerPort: 8008
        - containerPort: 8009
        - containerPort: 8010

        env:
        - name: VirtServerUser
          value: "virtserveradmin"
        - name: VirtServerPassword
          value: "XXXXXX"
        - name: "VirtServerUserRole"
          value: "admin"
        - name: ACCEPT_TOU
          value: "true"
        - name: VirtServerLicenseServer
          value: "10.162.0.40:1099"
      nodeSelector:
        agentpool: svpool
      tolerations:
      - key: "product"
        operator: "Equal"
        value: "taas-sv"
        effect: "NoSchedule"